Repository prezly/theme-kit-js, pull requests merged in 2023-11, with the labels that each got.

#423 [DEV-11883] Add Navigation component to Storybook
  package-lock.json
  packages/ui/package.json
  packages/ui/src/components/Breadcrumbs/Breadcrumbs.stories.tsx
  packages/ui/src/components/Button/Button.stories.tsx
  packages/ui/src/components/Button/Button.tsx
  packages/ui/src/components/Button/Icon.tsx
  packages/ui/src/components/Button/types.ts
  packages/ui/src/components/Dropdown/Dropdown.stories.tsx
  packages/ui/src/components/Dropdown/Dropdown.tsx
  packages/ui/src/components/GalleryTitle/GalleryTitle.stories.tsx
  packages/ui/src/components/Hero/Hero.stories.tsx
  packages/ui/src/components/Input/Input.stories.tsx
  packages/ui/src/components/Navigation/Navigation.stories.tsx
  packages/ui/src/components/Navigation/Navigation.tsx
  packages/ui/src/components/Navigation/__mocks__/categories.ts
  packages/ui/src/components/Navigation/__mocks__/index.ts
  packages/ui/src/components/Navigation/__mocks__/languages.ts
  packages/ui/src/components/Navigation/__mocks__/newsroom.ts
  packages/ui/src/components/Navigation/components/CategoriesDropdown.tsx
  packages/ui/src/components/Navigation/components/LanguagesDropdown.tsx
  packages/ui/src/components/Navigation/components/index.ts
  packages/ui/src/components/Navigation/index.ts
  packages/ui/src/components/Navigation/types.ts
  packages/ui/src/components/Navigation/util.ts
  packages/ui/src/components/PageTitle/PageTitle.stories.tsx
  packages/ui/src/components/SectionTitle/SectionTitle.stories.tsx
  packages/ui/src/components/StoryCard/StoryCard.stories.tsx
  packages/ui/src/components/StoryShareLinks/StoryShareLinks.stories.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/hooks/index.ts
  packages/ui/src/hooks/useDevice.ts
  packages/ui/tsconfig.json
Labels: enhancement

#425 [DEV-11852] Add Subscription CTA to storybook
  packages/ui/src/components/Input/Input.tsx
  packages/ui/src/components/SubscriptionCta/SubscriptionCta.stories.tsx
  packages/ui/src/components/SubscriptionCta/SubscriptionCta.tsx
  packages/ui/src/components/SubscriptionCta/index.ts
  packages/ui/src/components/index.ts
Labels: enhancement

#424 [DEV-11899] Add Links and Badges to Storybook
  package-lock.json
  packages/ui/.storybook/main.js
  packages/ui/package.json
  packages/ui/src/components/Button/Button.stories.tsx
  packages/ui/src/components/Button/Button.tsx
  packages/ui/src/components/Button/ButtonLink.tsx
  packages/ui/src/components/Button/types.ts
  packages/ui/src/components/Link/Icon.tsx
  packages/ui/src/components/Link/Link.stories.tsx
  packages/ui/src/components/Link/Link.tsx
  packages/ui/src/components/Link/index.ts
  packages/ui/src/components/Link/types.ts
  packages/ui/src/components/Navigation/Navigation.tsx
  packages/ui/src/components/index.ts
Labels: enhancement

#437 Feature - Strict locale code typings
  .github/workflows/test.yml
  .github/workflows/typecheck.yml
  package-lock.json
  package.json
  packages/core/package.json
  packages/core/src/intl/getShortestLocaleSlug.ts
  packages/core/src/intl/languages.ts
  packages/core/src/intl/locale.test.ts
  packages/core/src/intl/locale.ts
  packages/core/src/intl/matchLanguageByLocaleSlug.ts
  packages/core/src/seo/getAlternateLanguageLinks.test.ts
  packages/core/src/seo/getFallbackLocale.ts
  packages/core/src/seo/utils/bindLanguagesWithLocales.ts
  packages/core/src/utils/getLocalizedCategoryData.ts
  packages/intl/build-locales.js
  packages/intl/src/Locale.ts
  packages/intl/src/isLocaleSupported.ts
  packages/intl/src/locales.ts
  packages/nextjs/package.json
Labels: enhancement

#438 [DEV-11945] Refactor - Simplify `getAlternateLanguageLinks()` code
  package-lock.json
  package.json
  packages/core/package.json
  packages/core/src/seo/getAlternateLanguageLinks.ts
  packages/core/src/seo/utils/bindLanguagesWithLocales.ts
  packages/core/src/seo/utils/createAlternateLanguageLink.ts
  packages/core/src/seo/utils/index.ts
  packages/core/src/utils/getNewsroomLogoUrl.ts
Labels: refactor

#439 [DEV-11945] Feature - Add extra info to the `getAlternateLanguageLinks()` result
  packages/core/src/seo/getAlternateLanguageLinks.ts
  packages/core/src/seo/getFallbackLocale.test.ts
  packages/core/src/seo/getFallbackLocale.ts
  packages/core/src/seo/types.ts
Labels: enhancement

#436 [DEV-11853] Add Footer to Storybook
  package-lock.json
  packages/ui/package.json
  packages/ui/src/components/Boilerplate/Boilerplace.stories.tsx
  packages/ui/src/components/Boilerplate/Boilerplate.tsx
  packages/ui/src/components/Boilerplate/__mocks__/companyInformation.ts
  packages/ui/src/components/Boilerplate/__mocks__/index.ts
  packages/ui/src/components/Boilerplate/index.ts
  packages/ui/src/components/ContactCard/ContactCard.stories.tsx
  packages/ui/src/components/ContactCard/ContactCard.tsx
  packages/ui/src/components/ContactCard/__mocks__/contact.ts
  packages/ui/src/components/ContactCard/__mocks__/index.ts
  packages/ui/src/components/ContactCard/index.ts
  packages/ui/src/components/ContactCard/type.ts
  packages/ui/src/components/ContactCard/utils.ts
  packages/ui/src/components/Footer/DataRequestLink.tsx
  packages/ui/src/components/Footer/Footer.stories.tsx
  packages/ui/src/components/Footer/Footer.tsx
  packages/ui/src/components/Footer/SubFooter.tsx
  packages/ui/src/components/Footer/index.ts
  packages/ui/src/components/MadeWithPrezly/MadeWithPrezly.tsx
  packages/ui/src/components/MadeWithPrezly/index.ts
  packages/ui/src/components/StoryShareLinks/SocialMedia.tsx
  packages/ui/src/components/StoryShareLinks/index.ts
  packages/ui/src/components/index.ts
Labels: enhancement

#442 [DEV-11955] & [DEV-11956] Added Featured Media and Category components
  packages/ui/src/components/CategoryBlock/CategoryBlock.stories.tsx
  packages/ui/src/components/CategoryBlock/CategoryBlock.tsx
  packages/ui/src/components/CategoryBlock/index.ts
  packages/ui/src/components/GalleryMedia/GalleryMedia.stories.tsx
  packages/ui/src/components/GalleryMedia/GalleryMedia.tsx
  packages/ui/src/components/GalleryMedia/__mocks__/gallery.ts
  packages/ui/src/components/GalleryMedia/__mocks__/index.ts
  packages/ui/src/components/GalleryMedia/index.ts
  packages/ui/src/components/index.ts
Labels: enhancement

#443 [DEV-11970] Add shadows and blurs to Storybook
  packages/ui/src/stories/Shadows.stories.mdx
  packages/ui/tailwind.config.js
Labels: enhancement

#455 [DEV-11988] Provide a separate entry point for Sentry configs
  packages/nextjs/package.json
  packages/nextjs/src/index.ts
Labels: enhancement

#441 [DEV-11948] Add story blocks to Storybook
  package-lock.json
  packages/ui/package.json
  packages/ui/src/components/ContactCard/ContactCard.tsx
  packages/ui/src/components/ContactCard/type.ts
  packages/ui/src/components/ContentRenderer/ContentRenderer.css
  packages/ui/src/components/ContentRenderer/ContentRenderer.stories.tsx
  packages/ui/src/components/ContentRenderer/ContentRenderer.tsx
  packages/ui/src/components/ContentRenderer/__mocks__/index.ts
  packages/ui/src/components/ContentRenderer/__mocks__/story.ts
  packages/ui/src/components/ContentRenderer/components/Attachment/Attachment.tsx
  packages/ui/src/components/ContentRenderer/components/Attachment/DownloadLink.tsx
  packages/ui/src/components/ContentRenderer/components/Attachment/FileTypeIcon.tsx
  packages/ui/src/components/ContentRenderer/components/Attachment/index.ts
  packages/ui/src/components/ContentRenderer/components/Attachment/utils.ts
  packages/ui/src/components/ContentRenderer/components/Gallery.tsx
  packages/ui/src/components/ContentRenderer/components/Image.tsx
  packages/ui/src/components/ContentRenderer/components/RichText/Heading.tsx
  packages/ui/src/components/ContentRenderer/components/RichText/Html.tsx
  packages/ui/src/components/ContentRenderer/components/RichText/Link.tsx
  packages/ui/src/components/ContentRenderer/components/RichText/List.tsx
  packages/ui/src/components/ContentRenderer/components/RichText/Paragraph.tsx
  packages/ui/src/components/ContentRenderer/components/RichText/Quote.tsx
  packages/ui/src/components/ContentRenderer/components/RichText/index.ts
  packages/ui/src/components/ContentRenderer/components/StoryBookmark.tsx
  packages/ui/src/components/ContentRenderer/components/Variable.tsx
  packages/ui/src/components/ContentRenderer/components/index.ts
  packages/ui/src/components/ContentRenderer/index.ts
  packages/ui/src/components/index.ts
Labels: enhancement

#462 [DEV-11957] Refactor - Move `http` and `content-delivery` modules to the `core` package
  package-lock.json
  packages/core/package.json
  packages/core/src/content-delivery/ContentDelivery.ts
  packages/core/src/content-delivery/index.ts
  packages/core/src/fetch/CachedFetch.ts
  packages/core/src/fetch/cache/createCacheKeyFn.ts
  packages/core/src/fetch/cache/index.ts
  packages/core/src/fetch/cache/store.ts
  packages/core/src/fetch/cache/withCache.ts
  packages/core/src/fetch/index.ts
  packages/core/src/fetch/types.ts
  packages/core/src/http/HttpClient.ts
  packages/core/src/http/index.ts
  packages/core/src/index.ts
  packages/core/src/intl/index.ts
  packages/core/src/routing/getShortestLocaleSlug.ts
  packages/core/src/routing/isNumberCode.ts
  packages/core/src/routing/matchLanguageByLocaleSlug.ts
  packages/nextjs/package.json
  packages/nextjs/src/adapters/analytics/server.ts
  packages/nextjs/src/adapters/environment/server.ts
  packages/nextjs/src/adapters/intl/server.tsx
  packages/nextjs/src/adapters/metadata/lib/generateRootMetadata.ts
  packages/nextjs/src/adapters/metadata/lib/generateStoryPageMetadata.ts
  packages/nextjs/src/adapters/metadata/lib/types.ts
  packages/nextjs/src/adapters/metadata/lib/utils/generatePageMetadata.ts
  packages/nextjs/src/adapters/prezly/server.ts
  packages/nextjs/src/adapters/routing/lib/RoutingAdapter.client.tsx
  packages/nextjs/src/adapters/routing/lib/RoutingAdapter.server.ts
  packages/nextjs/src/adapters/routing/lib/createRouter.server.ts
  packages/nextjs/src/adapters/theme-settings/client.tsx
  packages/nextjs/src/adapters/theme-settings/server.ts
  packages/nextjs/src/adapters/types.ts
  packages/nextjs/src/client.ts
  packages/nextjs/src/content-delivery/ContentDelivery.ts
  packages/nextjs/src/content-delivery/index.ts
  packages/nextjs/src/http/HttpClient.ts
  packages/nextjs/src/index.ts
  packages/nextjs/src/middleware/IntlMiddleware.ts
  packages/nextjs/src/middleware/index.ts
  packages/nextjs/src/server.ts
  packages/nextjs/test/test-build.cjs
  packages/nextjs/test/test-build.mjs
  packages/nextjs/tsconfig.json
Labels: enhancement

#457 [DEV-11962] Storybook components QA
  package-lock.json
  packages/ui/src/components/Boilerplate/Boilerplate.tsx
  packages/ui/src/components/Button/Button.tsx
  packages/ui/src/components/Button/ButtonLink.tsx
  packages/ui/src/components/Button/Icon.tsx
  packages/ui/src/components/Dropdown/Dropdown.tsx
  packages/ui/src/components/GalleryMedia/GalleryMedia.tsx
  packages/ui/src/components/Hero/Hero.tsx
  packages/ui/src/components/Hero/components/HeroImage/HeroImage.tsx
  packages/ui/src/components/Link/Link.tsx
  packages/ui/src/components/Navigation/Navigation.stories.tsx
  packages/ui/src/components/Navigation/Navigation.tsx
  packages/ui/src/components/Navigation/components/CategoriesDropdown.tsx
  packages/ui/src/components/Navigation/components/LanguagesDropdown.tsx
  packages/ui/src/components/Navigation/types.ts
  packages/ui/src/components/StoryCard/StoryCard.tsx
  packages/ui/src/components/StoryCard/components/StoryImage/StoryImage.tsx
  packages/ui/src/components/StoryShareLinks/ShareButton.tsx
  packages/ui/src/components/StoryShareLinks/StoryShareLinks.tsx
  packages/ui/src/components/SubscriptionCta/SubscriptionCta.tsx
Labels: enhancement

#464 [DEV-11988] Fix - URL generation
  packages/core/package.json
  packages/intl/package.json
  packages/nextjs/src/adapters/routing/lib/RoutingAdapter.client.tsx
  packages/nextjs/src/adapters/routing/lib/RoutingAdapter.server.ts
  packages/nextjs/src/adapters/routing/lib/generateUrlFromPattern.test.ts
  packages/nextjs/src/adapters/routing/lib/generateUrlFromPattern.ts
Labels: bug

#472 [DEV-12012] Next.js 13 - Fix Request HTTP env headers are exposed as response headers
  packages/core/src/fetch/cache/withCache.ts
  packages/nextjs/src/middleware/IntlMiddleware.ts
Labels: bug
